#!/usr/bin/env bash
set -ueo pipefail
dateTime(){ date -u '+%Y-%m-%dT%H:%M:%SZ'; }
runpwd=$(pwd -P)
rundir=$(cd -P -- "$(dirname -- "$0")" && printf '%s\n' "$(pwd -P)")
cd "$rundir"
# {make.sh user} v1.0.0


CONTAINER_NAME="ustrip"
IMAGE_NAME="${CONTAINER_NAME}"
IMAGE_REPO="me/${IMAGE_NAME}"
IMAGE_TAG="latest"

run:nodemon () {
  nodemon -x "docker stop "${CONTAINER_NAME}";
   ./make.sh build \
   && ./make.sh docker"
}

run:build () {
  docker build --tag "${IMAGE_REPO}:${IMAGE_TAG}" .
}

run:docker () {
  docker run --tty \
   --env DEBUG=true \
   --rm \
   --name "${CONTAINER_NAME}" \
   "${IMAGE_REPO}:${IMAGE_TAG}" \
   "$@"
  #docker inspect "${CONTAINER_NAME}" | jq -r '.[0].NetworkSettings.IPAddress'
}

run:pages () {
  yarn build --base=/ustrip/
  current_commit=$(git show --oneline -s)
  cd dist
  git init
  git add -A
  git config --local user.name "mhio"
  git config --local user.email "37205532+mhio@users.noreply.github.com"
  git commit -m "deploy static build from $current_commit" .
  git push -f https://github.com/mhio/ustrip.git main:gh-pages
} 


# {make.sh common} v1.0.0
run:completion:words(){
  declare -F | while read -r line; do
    [ "${line:11:4}" = "run:" ] && [ "${line:11:15}" != "run:completion:" ] && echo "${line:15}"
  done
}
run:help(){
  set +x
  echo "Commands:"
  run:completion:words | while read -r line; do printf "  %s\n" "${line}"; done
  exit 1
}
[ -z "${1:-}" ] && run:help
[ "${1:11}" = "completion:" ] || set -x
run:"${1}" "${@:2}"

