#!/usr/bin/env bash
set -ueo pipefail
dateTime(){ date -u '+%Y-%m-%dT%H:%M:%SZ'; }
dateTimeShort(){ date -u '+%Y%m%d-%H%M%SZ'; }
runpwd=$(pwd -P)
rundir=$(cd -P -- "$(dirname -- "$0")" && printf '%s\n' "$(pwd -P)")
cd "$rundir"
# {make.sh user} v1.0.0


CONTAINER_NAME="ustrip"
IMAGE_NAME="${CONTAINER_NAME}"
IMAGE_REPO="me/${IMAGE_NAME}"
IMAGE_TAG="latest"

run:nodemon () {
  nodemon -x "docker stop "${CONTAINER_NAME}";
   ./make.sh build \
   && ./make.sh docker"
}

run:build () {
  docker build --tag "${IMAGE_REPO}:${IMAGE_TAG}" .
}

run:icons(){
  echo '// extract from @mdi/js/mdi.js' > src/icons.ts
  grep -w -e mdiLightbulb -e mdiMenu -e mdiContentCopy -e mdiOpenInNew node_modules/@mdi/js/mdi.js >> src/icons.ts
  cat src/icons.ts
}

run:docker () {
  docker run --tty \
   --env DEBUG=true \
   --rm \
   --name "${CONTAINER_NAME}" \
   "${IMAGE_REPO}:${IMAGE_TAG}" \
   "$@"
}
run:docker:getip(){
  docker inspect "${CONTAINER_NAME}" | jq -r '.[0].NetworkSettings.IPAddress'
}

run:pages () {
  cd "$rundir"
  rm -rvf dist/.git dist/assets dist/index.html
  rmdir dist
  yarn build --base=/ustrip/
  current_commit=$(git show --oneline -s)
  current_user=$(git config user.name)
  current_email=$(git config user.email)
  cd "$rundir"/dist
  g init
  g add -A
  g config --local user.name "${current_user}"
  g config --local user.email "${current_email}"
  g commit -m "deploy static build from $current_commit" .
  g push -f https://github.com/mhio/ustrip.git main:gh-pages
  cd "$rundir"
  g tag v$(dateTimeShort)
  g push --tags
} 
function g(){
  TZ= git "$@"
}


# {make.sh common} v1.0.0
run:completion:words(){
  declare -F | while read -r line; do
    [ "${line:11:4}" = "run:" ] && [ "${line:11:15}" != "run:completion:" ] && echo "${line:15}"
  done
}
run:help(){
  set +x
  echo "Commands:"
  run:completion:words | while read -r line; do printf "  %s\n" "${line}"; done
  exit 1
}
[ -z "${1:-}" ] && run:help
[ "${1:11}" = "completion:" ] || set -x
run:"${1}" "${@:2}"

